# Generated by Django 5.1.2 on 2024-10-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
